import React from 'react'
import Head from 'next/head'
import Header from "../components/Header";
import Banner from "../components/Banner";
import ProductFeed from "../components/ProductFeed";

function Home({products}) {

  return (
    <div className='bg-gray-100'>
      <Head>
        <title>Amazon 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header/>
        <main className='max-w-screen-2xl mx-auto'>
            <Banner/>
            <ProductFeed products={products}/>
        </main>
    </div>
  )
}

export async function getServerSideProps() {
    const response = await fetch('https://fakestoreapi.com/products');
    const products = await response.json();
    return {
        props: {
            products: products || null
        }
    }
}

export default Home;